### ISSUE TITLE
Sanitizing issue with oembed_facebook_app_id

### ISSUE THREAD

**Issue by mikeyarce** [Ayesh/WordPress-oEmbed-Facebook-Instagram#3]
Not a huge deal but wanted to make a note! :)

In this function:
https://github.com/Ayesh/WordPress-oEmbed-Facebook-Instagram/blob/master/src/Settings.php#L40-L45

The sanitization filter could be prone to human error.
For example, the value of `AAA1938BBBB914979`  would be sanitized as `1938914979`  which is an integer, but maybe not what the user was expecting.  

Even though most browsers are pretty good about validating the input first, it might be better to cast a type to the string like this:
`return (int) $string;` 

Instead of:

`return filter_var($string, FILTER_SANITIZE_NUMBER_INT);`

That way the return value would be `0`,  and the user would see that something they entered was not right.

**Comment by Ayesh** [comment]
Thanks for this one too, I updated the repo and also pushed to wordpress.org under the same tag. It's a new plugin, so I went ahead to overwrite the 1.0 tag.
