### ISSUE TITLE
Instagram Embed Code Question

### ISSUE THREAD

**Issue by broksonic21** [Ayesh/WordPress-oEmbed-Facebook-Instagram#4]
@Ayesh in @mikeyarce's code sample in issue #1 , the code is:

`(strpos($provider_url, 'https://graph.facebook.com/v8.0/oembed_') === false 
		|| strpos($provider_url, 'https://graph.facebook.com/v8.0/instagram_oembed') === false)`

with both being ===

but in the actual plugin (see https://github.com/Ayesh/WordPress-oEmbed-Plus/commit/87fc1236d659dd2a681dd9025226b4d9dae31945#diff-54825a668a335a7e9908af19652bb263R24 ), it is:

` strpos($provider_url, 'https://graph.facebook.com/v8.0/oembed_') === false
        || strpos($provider_url, 'https://graph.facebook.com/v8.0/instagram_oembed') !== false`

with the === for oembed, and !== for instagram.

Is this intentionally different? Just want to confirm which is correct.

**Comment by Ayesh** [comment]
Hi @broksonic21 - Thanks for the good catch. It was a bug indeed. I pushed 708cb18 that simplifies the provider URL check login to only look for the graph API URL, but not the specific end point.

**Comment by broksonic21** [comment]
This worked - thanks!
