### ISSUE TITLE
watch/?v=xxx format

### ISSUE THREAD

**Issue by smerriman** [Ayesh/WordPress-oEmbed-Facebook-Instagram#6]
Thanks for the plugin.

If I attempt to embed a video with a url of the format https://www.facebook.com/watch/?v=xxx , it does not work. (It didn't work in the past either).

Can you please add this as a valid provider - it's valid on Facebook's side, just not matched in WordPress.

**Comment by Ayesh** [comment]
Thanks for opening this issue. I have update the plugin, and this will be released with version `1.2` of this plugin, which will be released later today.
