### ISSUE TITLE
Multisite support for setting App ID and App Secret

### ISSUE THREAD

**Issue by paulshryock** [Ayesh/WordPress-oEmbed-Facebook-Instagram#7]
Is there a way to set the App ID and App Secret network-wide on a Multisite installation? There seems to be no Settings > Writing network admin screen. I tried setting up in `wp-config.php`, but upon testing, it's not working on individual sites on the network.

**Comment by paulshryock** [comment]
After additional testing, this plugin seems to not work at all on Multisite.

**Comment by paulshryock** [comment]
I needed to remove App credentials from `wp-config.php` and add them to individual sites in Settings > Writing. But for a network with hundreds of sites... it'd be nice to have a network-wide option.

**Comment by Ayesh** [comment]
Hi @paulshryock - the PHP constant setup in `wp-config.php` is intended to assist in multisite setups. 

Just to eliminate what I think is the likely cause, could you try adding the following to the config file?

```php
define('OEMBED_PLUS_FACEBOOK_APP_ID', '<App ID Here>');
define('OEMBED_PLUS_FACEBOOK_SECRET', '<Secret Here>');
```

This should provide credentials, and can be confirmed from the Writing options page. It will not show the API keys, but should confirm that settings are entered in the wp-config file.

**Comment by paulshryock** [comment]
You're right, this worked. I was testing in Firefox with privacy settings that blocked it. Worked in Chrome. This issue can be closed.

**Comment by Ayesh** [comment]
Firefox ♥️.
